{"ast":null,"code":"import _classCallCheck from\"G:\\\\Github\\\\creativehire\\\\frontend\\\\gui\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/classCallCheck\";import _createClass from\"G:\\\\Github\\\\creativehire\\\\frontend\\\\gui\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/createClass\";import _possibleConstructorReturn from\"G:\\\\Github\\\\creativehire\\\\frontend\\\\gui\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/possibleConstructorReturn\";import _getPrototypeOf from\"G:\\\\Github\\\\creativehire\\\\frontend\\\\gui\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/getPrototypeOf\";import _inherits from\"G:\\\\Github\\\\creativehire\\\\frontend\\\\gui\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/inherits\";import React from'react';var ErrorBoundary=/*#__PURE__*/function(_React$Component){_inherits(ErrorBoundary,_React$Component);function ErrorBoundary(props){var _this;_classCallCheck(this,ErrorBoundary);_this=_possibleConstructorReturn(this,_getPrototypeOf(ErrorBoundary).call(this,props));_this.state={hasError:false};return _this;}_createClass(ErrorBoundary,[{key:\"componentDidCatch\",value:function componentDidCatch(error,errorInfo){// You can also log the error to an error reporting service\nconsole.log(error,errorInfo);}},{key:\"render\",value:function render(){if(this.state.hasError){// You can render any custom fallback UI\nreturn React.createElement(\"h1\",null,\"Something went wrong.\");}return this.props.children;}}],[{key:\"getDerivedStateFromError\",value:function getDerivedStateFromError(error){// Update state so the next render will show the fallback UI.\nreturn{hasError:true};}}]);return ErrorBoundary;}(React.Component);export default ErrorBoundary;","map":{"version":3,"sources":["G:/Github/creativehire/frontend/gui/src/components/ErrorBoundary.js"],"names":["React","ErrorBoundary","props","state","hasError","error","errorInfo","console","log","children","Component"],"mappings":"6zBAAA,MAAOA,CAAAA,KAAP,KAAkB,OAAlB,C,GAGMC,CAAAA,a,mFACF,uBAAYC,KAAZ,CAAmB,+CACjB,+EAAMA,KAAN,GACA,MAAKC,KAAL,CAAa,CAAEC,QAAQ,CAAE,KAAZ,CAAb,CAFiB,aAGlB,C,sFAOiBC,K,CAAOC,S,CAAW,CAClC;AACAC,OAAO,CAACC,GAAR,CAAYH,KAAZ,CAAmBC,SAAnB,EACD,C,uCAEQ,CACP,GAAI,KAAKH,KAAL,CAAWC,QAAf,CAAyB,CACvB;AACA,MAAO,uDAAP,CACD,CAED,MAAO,MAAKF,KAAL,CAAWO,QAAlB,CACD,C,4EAjB+BJ,K,CAAO,CACrC;AACA,MAAO,CAAED,QAAQ,CAAE,IAAZ,CAAP,CACD,C,2BATuBJ,KAAK,CAACU,S,EA0BhC,cAAeT,CAAAA,aAAf","sourcesContent":["import React from 'react';\r\n\r\n\r\nclass ErrorBoundary extends React.Component {\r\n    constructor(props) {\r\n      super(props);\r\n      this.state = { hasError: false };\r\n    }\r\n  \r\n    static getDerivedStateFromError(error) {\r\n      // Update state so the next render will show the fallback UI.\r\n      return { hasError: true };\r\n    }\r\n  \r\n    componentDidCatch(error, errorInfo) {\r\n      // You can also log the error to an error reporting service\r\n      console.log(error, errorInfo);\r\n    }\r\n  \r\n    render() {\r\n      if (this.state.hasError) {\r\n        // You can render any custom fallback UI\r\n        return <h1>Something went wrong.</h1>;\r\n      }\r\n  \r\n      return this.props.children; \r\n    }\r\n  }\r\n\r\n  export default ErrorBoundary;"]},"metadata":{},"sourceType":"module"}